name = "SphericalHarmonicTransforms"
uuid = "b59b3b60-d6a7-4e29-bf1f-fd1ceecb3c6a"
author = ["Justin Willmert <justin@willmert.me>"]
version = "0.1.0"

[deps]
AssociatedLegendrePolynomials = "2119f1ac-fb78-50f5-8cc0-dda848ebdb19"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
AssociatedLegendrePolynomials = "1"
Compat = "3.25, 4"
FFTW = "1"
julia = "1.2"
